### ISSUE TITLE
Trailing forward slash in Mealie url causes recipe links to fail

### ISSUE THREAD

**Issue by strawy** [michael-genson/Unified-Shopping-List#33]
When configuring mealie settings, accidently adding a / to the end of the Mealie URL will cause the extra / to be added into the recipe url to the todoist description.

![image](https://github.com/michael-genson/Unified-Shopping-List/assets/4090653/608dff1f-adbd-4376-9e90-2086403be7e2)

![image](https://github.com/michael-genson/Unified-Shopping-List/assets/4090653/54b5267a-5565-455d-9698-a7dd6620b7c1)

**Comment by michael-genson** [comment]
Ah yup, sure does. I'll get that fixed, thanks for the report!
