### ISSUE TITLE
Alexa discontinueing Rest API

### ISSUE THREAD

**Issue by Insayne84** [michael-genson/Unified-Shopping-List#36]
Hello,

I am wondering if you seen [Amazons Announcement](https://developer.amazon.com/en-US/docs/alexa/custom-skills/access-the-alexa-shopping-and-to-do-lists.html) regarding discontinueing the REST API. Specifically:

> Warning: Starting July 1, 2024, you will no longer be able to use [List skills](https://developer.amazon.com/en-US/docs/alexa/list-skills/list-skills-overview.html) or the [List Management REST API](https://developer.amazon.com/en-US/docs/alexa/list-skills/list-management-api-reference.html) to access Alexa lists, i.e., the [Alexa Shopping and To-Do lists](https://developer.amazon.com/en-US/docs/alexa/custom-skills/access-the-alexa-shopping-and-to-do-lists.html), in your skills or apps. For other ways to build custom voice experiences, see [Steps to Build a Custom Skill](https://developer.amazon.com/en-US/docs/alexa/custom-skills/steps-to-build-a-custom-skill.html). Please [contact us](https://developer.amazon.com/en-US/docs/alexa/ask-overviews/contact-us.html) if you have any questions.

Will USL continue to work after this "update" on July 1st?

**Comment by michael-genson** [comment]
Whelp, thanks for the heads up! Silly of me to expect Amazon to notify developers using the REST API that they're getting rid of it.

> Will USL continue to work

Without any changes, no, but I will look into it. We're depending on [my custom Alexa skill](https://github.com/michael-genson/Unified-Shopping-List-Helper) which will have to be modified. Hopefully it's still possible.

**Comment by michael-genson** [comment]
Looks like it's not going to be possible, sadly. Todoist put up a notice: https://todoist.com/help/articles/use-amazon-alexa-with-todoist-OKO3lHwv

**Comment by Insayne84** [comment]
Yeah i saw....

While i may be sad/pissed over it, i feel even worse for you for having put time, effort and providing it as a service to others for free just for them to pull the plug like that. 

I'm really sorry i broke the news like this to you. Thank you for your work, it is appreciated 😊

**Comment by michael-genson** [comment]
Well I'm infinitely more glad that you brought my attention to it, rather than finding out on July 1st. I'll probably be turning my attention over to Home Assistant, since HA has voice assistant support. [It's been requested on USL](https://github.com/michael-genson/Unified-Shopping-List/issues/32) quite a bit anyway.

**Comment by Insayne84** [comment]
Yeah, i just switched to HA as well to make this work and am ditching Alexa.

I´ve come across this [Integration](https://github.com/andrew-codechimp/HA-Mealie?tab=readme-ov-file) for HACS.
